default: &default
  dispatchers:
    - polling_interval: 5
      batch_size: <%= ENV.fetch("SOLID_QUEUE_BATCH_SIZE", 100) %>
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("SOLID_QUEUE_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
