# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  contract_due_reminder:
    class: ContractDueReminderJob
    schedule: every day at 1am

  invoice_creation_reminder:
    class: InvoiceCreationReminderJob
    schedule: every day at 1am

  contract_due_today:
    class: ContractDueTodayJob
    schedule: every day at 2am

  contract_overdue_close:
    class: ContractOverdueCloseJob
    schedule: every day at 2am

  request_overdue_expire:
    class: RequestOverdueExpireJob
    schedule: every day at 3am

  cleanup_notifications:
    class: CleanupNotificationsJob
    args: [ { read_days: 30, unread_days: 180 } ]
    schedule: every day at 3:30am

  invoice_due_today:
    class: InvoiceDueTodayJob
    schedule: every day at 7am

  invoice_overdue_check:
    class: InvoiceOverdueCheckJob
    schedule: every day at 7:30am
